### ISSUE TITLE
 Redis Connection Error and Unexpected Exit of update_00 Process

### ISSUE THREAD

**Issue by JotaPePG** [MISP/misp-docker#162] opened 2024-10-03 19:20 UTC
I'm currently in the process of transitioning from Coolacid's MISP Docker image to the official MISP Docker image (ghcr.io/misp/misp-docker/misp-core:latest) within Kubernetes cluster managed by Rancher 2.8. During this migration, I've encountered two persistent issues related to Redis integration and background job processes.

Error Logs:
Redis Connection Error:
```shell
Warning: Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name or service not known in [/var/www/MISP/app/Lib/Tools/BackgroundJobsTool.php, line 676]
```
Unexpected Exit of update_00 Process:
```shell
INFO spawned: 'update_00' with pid 5632
INFO success: update_00 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
WARN exited: update_00 (exit status 1; not expected)
```
This error repeats itself over and over again.

What I've Done

Verified Redis Deployment:
Ensured that the Redis pod is running without issues.
Confirmed that the Redis service (misp-redis-service) is correctly defined and accessible within the cluster.

Checked MISP Configuration:
Updated the MISP Deployment YAML to include the correct REDIS_HOST (misp-redis-service) and REDIS_PORT (6379) environment variables.
Utilized ConfigMaps and Secrets to manage non-sensitive and sensitive configurations, respectively.

Tested Connectivity:
Accessed the MISP pod and successfully connected to Redis using redis-cli, receiving the expected PONG response.

There is any resources or advice on learning how to successfully migrate from Coolacid's MISP to the official MISP?

**Comment by ostefano** [comment] 2024-10-03 21:41
Yeah, you need to make sure that Redis has a password set since that is mandatory.

I will close this since the issue is not with the image but rather with the upgrade process, and for that I would suggest you to ask gitter/matrix chan for help.

**Closed as not planned** 2024-10-03 21:41 UTC
