### ISSUE TITLE
Problem getting web server up

### ISSUE THREAD

**Issue by DkYSwe** [MISP/misp-docker#6] opened 2023-12-18 15:18 UTC
Hi,

I yesterday downloaded (existing images) and tried to get the containers up and running (RHEL8). I run into a problem to get the web server up and running.

misp-core-1     | nginx: [error] open() "/run/nginx.pid" failed (2: No such file or directory)
misp-core-1     | sudo: unable to send audit message: Operation not permitted ### Debut msg?
misp-core-1     | Error: Setting change rejected. ### Debut msg?
misp-core-1     | The setting change was rejected. MISP considers the requested setting value as invalid and would lead to the following error:
misp-core-1     |
misp-core-1     | "Invalid baseurl, please make sure that the protocol is set."
misp-core-1     |
misp-core-1     | If you still want to force this change, please supply the --force argument.

Everything else looks fine (not running the smtp container)
Updated image names since Podman adds "localhost".

```
See below for diff between my config and untouched config file.
< #  mail:
< #    image: ixdotai/smtp
< #    environment:
< #      - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
< #      - "SMARTHOST_PORT=${SMARTHOST_PORT}"
< #      - "SMARTHOST_USER=${SMARTHOST_USER}"
< #      - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
< #      - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"
---
>   mail:
>     image: ixdotai/smtp
>     environment:
>       - "SMARTHOST_ADDRESS=${SMARTHOST_ADDRESS}"
>       - "SMARTHOST_PORT=${SMARTHOST_PORT}"
>       - "SMARTHOST_USER=${SMARTHOST_USER}"
>       - "SMARTHOST_PASSWORD=${SMARTHOST_PASSWORD}"
>       - "SMARTHOST_ALIASES=${SMARTHOST_ALIASES}"
15c15
<     image: localhost/redis:7.2
---
>     image: redis:7.2
19c19
<     image: localhost/mariadb:10.11
---
>     image: mariadb:10.11
22,24c22,24
<       - "MYSQL_USER=${MYSQL_USER:-MISP_USER}"
<       - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-MISP_PWD}"
<       - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-MISP_ROOTPWD}"
---
>       - "MYSQL_USER=${MYSQL_USER:-misp}"
>       - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}"
>       - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}"
67,69c67,68
<       #- "ADMIN_EMAIL=${ADMIN_EMAIL}"
<       - "ADMIN_EMAIL=OUREMAIL@OURDOMAIN"
<       - "ADMIN_PASSWORD=OUR_PWD"
---
>       - "ADMIN_EMAIL=${ADMIN_EMAIL}"
>       - "ADMIN_PASSWORD=${ADMIN_PASSWORD}"
95,96c94,95
<       - "MYSQL_USER=${MYSQL_USER:-MISP_USER}"
<       - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-MISP_PWD}"
---
>       - "MYSQL_USER=${MYSQL_USER:-misp}"
>       - "MYSQL_PASSWORD=${MYSQL_PASSWORD:-example}"
```

Do you see any apparently wrong? Any hints welcome. 

//Daniel

**Comment by ostefano** [comment] 2023-12-18 15:41
Please format your diff accordingly, and read the Troubleshooting section.

As this is not a bug with misp-docker, but more a deployment issue, I am closing this.

Feel free to join the Docker room in Gitter to ask the community for support.

**Comment by ostefano** [comment] 2023-12-18 15:46
Actually, there might be something I can improve in the documentation.

What did you set here `HOSTNAME=` ?

**Comment by DkYSwe** [comment] 2023-12-18 16:23
I had exported HOSTNAME before running docker-compose up.
Did a try now with a variable instead in docker-compos.yml, - "HOSTNAME=our_hostname" - no difference.

**Comment by ostefano** [comment] 2023-12-18 16:30
Can you verify that?

**Comment by DkYSwe** [comment] 2023-12-18 17:15
> Can you verify that?
Sorry, verify what?

**Comment by ostefano** [comment] 2023-12-18 17:23
That the value is correctly initialised.

Have you tried adding "https://" (http://) to the hostname?
I agree that the variable name (`HOSTNAME`) is actually misleading.

I will fix that.

**Comment by DkYSwe** [comment] 2023-12-18 17:55
Still no change and the same errors.

**Comment by ostefano** [comment] 2023-12-18 18:23
Did you try setting it explicitly inside the `.env` file?

**Comment by DkYSwe** [comment] 2023-12-18 19:24
I found the root cause and it was all me. :(
While hurrying to get the environment up, I hadn't created the .env file. 
I populated it and did my changes and it seems to work just fine.

Sorry for taking your time.

Keep up the good work!

/Daniel

**Closed as completed** 2023-12-18 19:31 UTC
