### ISSUE TITLE
cred leakage in entrypoint_fpm.sh

### ISSUE THREAD

**Issue by wmax641** [MISP/misp-docker#138] opened 2024-09-04 05:05 UTC
`entrypoint_fpm.sh` prints Redis password to stdout

 PR #137  for simple remediation 

```bash
~ echo "Configure PHP | Setting 'session.save_path = '$(echo $REDIS_HOST | grep -E '^\w+://' || echo tcp://$REDIS_HOST):6379?auth=${REDIS_PASSWORD}'"

Configure PHP | Setting 'session.save_path = 'tcp://redis.asdf.local:6379?auth=hello123!'
```

**Comment by ostefano** [comment] 2024-09-04 07:13
I consider this a non-issue since this is the intended behavior (see my comment here https://github.com/MISP/misp-docker/pull/137).

I will close this, but happy to merge the PR if the behavior is made configurable and all leakages are handled.

**Closed as not planned** 2024-09-04 07:13 UTC
